language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - TYPO3_VERSION=cms=^7.6 TESTING_VERSION=^2.0 MINIMUM_STABILITY=stable COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=cms=^8.7 TESTING_VERSION=^3.0 MINIMUM_STABILITY=stable COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=cms-core=^9.5 TESTING_VERSION=^4 MINIMUM_STABILITY=stable COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=cms-core=^10.1 TESTING_VERSION=dev-master MINIMUM_STABILITY=dev COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=cms-core=dev-master TESTING_VERSION=dev-master MINIMUM_STABILITY=dev COVERAGE=0 FUNCTIONAL=0

matrix:
  exclude:
    - env: TYPO3_VERSION=cms-core=^9.5 TESTING_VERSION=^4 MINIMUM_STABILITY=stable COVERAGE=0 FUNCTIONAL=0
      php: 7.0
    - env: TYPO3_VERSION=cms-core=^10.1 TESTING_VERSION=dev-master MINIMUM_STABILITY=dev COVERAGE=0 FUNCTIONAL=0
      php: 7.0
    - env: TYPO3_VERSION=cms-core=dev-master TESTING_VERSION=dev-master MINIMUM_STABILITY=dev COVERAGE=0 FUNCTIONAL=0
      php: 7.0
    - env: TYPO3_VERSION=cms-core=^9.5 TESTING_VERSION=^4 MINIMUM_STABILITY=stable COVERAGE=0 FUNCTIONAL=0
      php: 7.1
    - env: TYPO3_VERSION=cms-core=^10.1 TESTING_VERSION=dev-master MINIMUM_STABILITY=dev COVERAGE=0 FUNCTIONAL=0
      php: 7.1
    - env: TYPO3_VERSION=cms-core=dev-master TESTING_VERSION=dev-master MINIMUM_STABILITY=dev COVERAGE=0 FUNCTIONAL=0
      php: 7.1
    - env: TYPO3_VERSION=cms=^7.6 TESTING_VERSION=^2.0 MINIMUM_STABILITY=stable COVERAGE=0 FUNCTIONAL=0
      php: 7.2
    - env: TYPO3_VERSION=cms=^7.6 TESTING_VERSION=^2.0 MINIMUM_STABILITY=stable COVERAGE=0 FUNCTIONAL=0
      php: 7.3
  include:
    - env: TYPO3_VERSION=cms=^7.6 TESTING_VERSION=^2.0 MINIMUM_STABILITY=stable COVERAGE=1 FUNCTIONAL=0
      php: 7.0
    - env: TYPO3_VERSION=cms-core=^9.5 TESTING_VERSION=^4 MINIMUM_STABILITY=stable COVERAGE=1 FUNCTIONAL=0
      php: 7.2
  allow_failures:
    - env: TYPO3_VERSION=cms-core=^10.1 TESTING_VERSION=dev-master MINIMUM_STABILITY=dev COVERAGE=0 FUNCTIONAL=0
    - env: TYPO3_VERSION=cms-core=dev-master TESTING_VERSION=dev-master MINIMUM_STABILITY=dev COVERAGE=0 FUNCTIONAL=0

notifications:
  email:
    on_success: never
    on_failure: never

sudo: false

addons:
  apt:
    packages:
      - parallel
      - moreutils

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  # Switch stability for dev-master of typo3
  - composer config minimum-stability $MINIMUM_STABILITY
  # Add patch for v10 and master
  - >
    if [[ "$TYPO3_VERSION" == "cms-core=dev-master" || "$TYPO3_VERSION" == "cms-core=^10.1" ]]; then
      jq --indent 4 '.extra.patches."nimut/testing-framework"."Patch for TYPO3 v10: https://github.com/Nimut/testing-framework/pull/118" = "Build/Patches/nimut-testing-framework-118.diff"' composer.json | sponge composer.json
    fi
  # Installs TYPO3
  - composer require typo3/$TYPO3_VERSION nimut/testing-framework=$TESTING_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export "TYPO3_PATH_WEB"=$PWD/.Build/Web;
  # Locating UnitTests.xml
  - export "UNIT_XML"='.Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml'
  # Symlink TYPO3-Core
  - ln -nfs .Build/vendor/typo3/cms/typo3 typo3


script:
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --colors -c $UNIT_XML Tests/Unit
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --coverage-clover=unittest-coverage.clover --colors -c $UNIT_XML Tests/Unit
    fi
  - >
   if [[ "$COVERAGE" == "1" ]]; then
     echo;
     echo "Uploading code coverage results";
     wget https://scrutinizer-ci.com/ocular.phar
     php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
   fi
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" ! -path "./scripts/*" ! -path "./typo3_src/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

